### ISSUE TITLE
Hab Builder is an deployable Automate product that requires no external deps                                        

### ISSUE THREAD

**Issue by ryancragun** [chef/automate#1782]
We need to be able to launch the Hab builder either as a standalone or automated                                    
integrated service.                                                                                                 
                                                                                                                    
## Known required services:                                                                                            
* automate-load-balancer                                                                                            
* automate-gateway                                                                                                  
* automate-postgresql                                                                                               
* automate-pg-gateway                                                                                               
* automate-dex                                                                                                      
* backup-gateway                                                                                                    
* hab-builder-memcached                                                                                             
* hab-builder-minio                                                                                                                                                                                                   
  config:
```toml                                                                                                           
    key_id = "$MINIO_ACCESS_KEY"                                                                                    
    secret_key = "$MINIO_SECRET_KEY"                                                                                
    bucket_name = "$MINIO_BUCKET"
```                                                                                   
* hab-builder-api                                                                                                   
  * config:
```toml                                                                                                         
    log_level="error,tokio_core=error,tokio_reactor=error,zmq=error,hyper=error"                                    
    jobsrv_enabled = false                                                                                          
                                                                                                                    
    [http]                                                                                                          
    handler_count = 10                                                                                              
                                                                                                                    
    [api]                                                                                                           
    features_enabled = "$FEATURES_ENABLED"                                                                          
    targets = ["x86_64-linux", "x86_64-linux-kernel2", "x86_64-windows"]                                            
                                                                                                                    
    [depot]                                                                                                         
    jobsrv_enabled = false                                                                                          
                                                                                                                    
    [oauth]                                                                                                         
    provider = "$OAUTH_PROVIDER"                                                                                    
    userinfo_url = "$OAUTH_USERINFO_URL"                                                                            
    token_url = "$OAUTH_TOKEN_URL"                                                                                  
    redirect_url = "$OAUTH_REDIRECT_URL"                                                                            
    client_id = "$OAUTH_CLIENT_ID"                                                                                  
    client_secret = "$OAUTH_CLIENT_SECRET"                                                                          
                                                                                                                    
    [s3]                                                                                                            
    backend = "minio"                                                                                               
    key_id = "$MINIO_ACCESS_KEY"                                                                                    
    secret_key = "$MINIO_SECRET_KEY"                                                                                
    endpoint = "$MINIO_ENDPOINT"                                                                                    
    bucket_name = "$MINIO_BUCKET"                                                                                   
                                                                                                                    
    [artifactory]                                                                                                   
    api_url = "$ARTIFACTORY_API_URL"                                                                                
    api_key = "$ARTIFACTORY_API_KEY"                                                                                
    repo = "$ARTIFACTORY_REPO"                                                                                      
                                                                                                                    
    [memcache]                                                                                                      
    ttl = 1                                                                                                         
                                                                                                                    
    [datastore]                                                                                                     
    password = "$PGPASSWORD"                                                                                        
    connection_timeout_sec = 5                                                                                      
    host = "$PG_HOST"                                                                                               
    port = $PG_PORT
```                                                                                                 
  * Also needs a bldr key: (hab user key generate bldr)                                                             
* hab-builder-api-proxy (currently includes UI assets, we may or may not want to break this out)                                    
  config:
```toml                                                                                                           
    log_level="info"                                                                                                
    enable_builder = false                                                                                          
    app_url = "${APP_URL}"                                                                                          
                                                                                                                    
    [oauth]                                                                                                         
    provider = "$OAUTH_PROVIDER"                                                                                    
    client_id = "$OAUTH_CLIENT_ID"                                                                                  
    authorize_url = "$OAUTH_AUTHORIZE_URL"                                                                          
    redirect_url = "$OAUTH_REDIRECT_URL"                                                                            
    signup_url = "$OAUTH_SIGNUP_URL"                                                                                
                                                                                                                    
    [nginx]                                                                                                         
    max_body_size = "2048m"                                                                                         
    proxy_send_timeout = 180                                                                                        
    proxy_read_timeout = 180                                                                                        
    enable_gzip = true                                                                                              
    enable_caching = true                                                                                           
                                                                                                                    
    [http]                                                                                                          
    keepalive_timeout = "180s"                                                                                      
                                                                                                                    
    [server]                                                                                                        
    listen_tls = $APP_SSL_ENABLED                                                                                   
                                                                                                                    
    [analytics]                                                                                                     
    enabled = $ANALYTICS_ENABLED                                                                                    
    company_id = "$ANALYTICS_COMPANY_ID"                                                                            
    company_name = "$ANALYTICS_COMPANY_NAME"                                                                        
    write_key = "$ANALYTICS_WRITE_KEY"
```                                                                              
  * Also needs ssl-certificate.{crt,key}                                                                            
                                                                                                                    
## Questions                                                                                                           
* How do we want to handle building the services? Should we wrap habitat core                                       
  packages or recreate the plans tailored to our use case?                                                          
* How many new database connections should we expect? Should we change the default                                    
  max?                                                                                                              
* The builder-api-proxy (and perhaps other services) don't log to journald                                          
* Log levels and debug logging?                                                                                     
                                                                                                                    
## Acceptance Criteria:                                                                                                
* All of the required services are deployed when configured to use the 'hab-builder',                                    
 or 'hab-depot' (or something like that) product code.                                                              
* All services should properly bind to their dependencies                                                           
* User must accept the correct EULAs
* We should figure out what to calls these services
