### ISSUE TITLE
Updates due to inspec attributes to inputs change

### ISSUE THREAD

**Issue by alexpop** [chef/automate#194]
For a profile with `inspec.yml` containing these attributes:
```
attributes:
  - name: bucket_name
    description: Required cloud bucket name
    type: string
    required: true
    default: 'test'

  - name: retries
    description: How many times to retry
    type: numeric
    required: false
    default: 3  
```

`inspec json` output returns both the legacy `attributes` array:
```
"attributes": [
  {
    "name": "bucket_name",
    "description": "Required cloud bucket name",
    "type": "string",
    "required": true,
    "default": "test"
  },
  {
    "name": "retries",
    "description": "How many times to retry",
    "type": "numeric",
    "required": false,
    "default": 3
  }
```

and the new `inputs` array:
```
"inputs": [
  {
    "name": "bucket_name",
    "options": {
      "description": "Required cloud bucket name",
      "type": "string",
      "required": true,
      "value": "test"
    }
  },
  {
    "name": "retries",
    "options": {
      "description": "How many times to retry",
      "type": "numeric",
      "required": false,
      "value": 3
    }
  }
```

Observed this on inspec `3.7.11` and `3.9.0`.

The automate ingestion logic, elasticsearch mappings and APIs only understand the `attributes` array at the moment.

Will need to prioritize the backend work required by this `attributes` -> `inputs` change in inspec. It requires changes to: elasticsearch mappings, data migration, ingestion logic, API logic, reponses and UI rendering.
