### ISSUE TITLE
Expired compliance waivers displaying as waived when `run: true`

### ISSUE THREAD

**Issue by rmoles** [chef/automate#4342]
## Describe the bug
When running an Inspec profile with a waiver with a date in the past and `run: true`, Automate will display the control as waived despite the waiver being expired.

example inspec waiver:
```
  xccdf_org.cisecurity.benchmarks_rule_1.1.1.1_Ensure_mounting_of_cramfs_filesystems_is_disabled:
    run: true
    expiration_date: 2015/10/21
```

example of the Inspec JSON output:
```
{"name":"xccdf_org.cisecurity.benchmarks_rule_1.1.1.1_Ensure_mounting_of_cramfs_filesystems_is_disabled","options":{"value":{"run":true,"expiration_date":"2015/10/21","skipped_due_to_waiver":false,"message":""}}}
```

As can be seen in the JSON output, Inspec is reporting that the control has not been waived as the expiration date has passed. This proves to me that Inspec is running the control as expected and there is some logic within Automate that is always setting the control as waived when `run: true`.

I have tested this with `run: false` and the control appears un-waived in the Automate UI.

## To Reproduce
Set an Inspec waiver similar to above with `run: true` and any expiration date in the past eg. `expiration_date: 2015/10/21`

## Expected behavior
I would expect that the control would appear as passed/failed/skipped as normal as the waiver has expired

## Screenshots
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/15362434/93225377-0f174a00-f76a-11ea-82e2-f7ace5687d4f.png">

## Versions (please complete the following information):
- OS: rhel8
- Browser: Safari
- Automate Build Number: 20200908235050

**Comment by alexpop** [comment]
Thank you for the solid bug report Ross!

This is the code that decides during ingestion in Automate if a control is waived or not:

https://github.com/chef/automate/blob/master/components/compliance-service/ingest/events/compliance/helper_methods.go#L43

Key to this bug is the following condition:
```go
!strings.HasPrefix(control.WaiverData.Message, "Waiver expired")
```

We rely on the `control>waiver_data>message` to tell us if the waiver `expiration_date` was due or not when the scan was done.

For example, for the following waiver yaml:
```yaml
02-tmp-files:
  run: false
  expiration_date: 2015/10/21
```

InSpec returned:
```json
          "waiver_data": {
            "run": false,
            "expiration_date": "2015/10/21",
            "skipped_due_to_waiver": false,
            "message": "Waiver expired on 2015-01-01 00:00:00 +0000, evaluating control normally"
          },
          "results": [
            {
              "status": "failed",
              "code_desc": "File /tmp/file1.txt is expected to be file",
              "run_time": 0.026289227,
              "start_time": "2020-09-21T15:15:51+01:00",
              "message": "expected `File /tmp/file1.txt.file?` to return true, got false"
            },
...
```

Changing `run` to `true` in waiver yaml:
```yaml
02-tmp-files:
  run: true
  expiration_date: 2015/10/21
```

InSpec returned:
```json
          "waiver_data": {
            "run": true,
            "expiration_date": "2015/10/21",
            "skipped_due_to_waiver": false,
            "message": ""
          },
          "results": [
            {
              "status": "failed",
              "code_desc": "File /tmp/file1.txt is expected to be file",
              "run_time": 0.03090404,
              "start_time": "2020-09-21T15:26:44+01:00",
              "message": "expected `File /tmp/file1.txt.file?` to return true, got false"
            },
...
```

As can be seen, `control>waiver_data>message` in the above report is blank, making Automate ingestion mark the control as waived. In my opinion the bug is in InSpec for not returning the `Waiver expired on...` message for the control.

**Comment by vjeffrey** [comment]
we discussed this in standup.
given that the only difference in inputs in the two described cases is `run: true` vs `run:false`, i would expect the output to be exactly the same excepting the value of run.
so, two things:
1) let's get an issue open on the inspec repo to fill in that msg text
2) let's also open an issue in inspec where we can work on a more programmatically-readable way to denote that a control is waived. We really can't depend with confidence on string parsing for that

**Comment by rmoles** [comment]
Thanks, @alexpop and @vjeffrey for looking into this. I agree that this is probably best solved downstream in inspec with some supplementary work in Automate.
IMO it would be good to change up the fields slightly as the current functionality is slightly counter-intuitive.
Perhaps something along these lines would make sense...
```
  # this could also just be defined as run: true or with no definition at all, as the control will run as normal
  run_true_waived_false:
    run: true
    waived: false
  # this would execute the control as normal but would appear as waived in automate and in the report
  run_true_waived_true:
    run: true
    waived: true
    expiration_date: 2015/10/21
  # this could be equivalent to waived: true or be a separate designation of Disabled
  run_false:
    run: false
    expiration_date: 2015/10/21
  # this is the equivalent to waived: true where the control is not executed at all
  run_false_waived_true:
    run: false
    waived: false
    expiration_date: 2015/10/21
```
